function makeCpp( fn )

    mex( fn, '-I/usr/not-backed-up/OpenCV-2.1.0/include/opencv', ...
             '-L/usr/not-backed-up/OpenCV-2.1.0/lib', '-lcv', ...
             '-lcvaux', '-lcxcore', '-lhighgui', '-lstdc++', ...
             '-lavcodec', '-lavformat', '-lavutil');
end