options = optimset( 'Display', 'off', ...
                    'Algorithm',{'levenberg-marquardt',.005}, ...
                    'MaxFunEvals', 10000, ...
                    'MaxIter', 1000, ...
                    'TolFun',1e-12 ...
                   );